before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
before_install:
  - echo "yes" | gem uninstall json
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
script:
  - "export DISPLAY=:99.0"
  - "bundle exec rspec spec"
branches:
  only:
    - 1-2-stable
notifications:
  email:
    - ryan@spreecommerce.com
rvm:
  - 1.8.7
  - 1.9.3

